name: Clojure CI

on: [push]

jobs:

  clojure_build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Prepare java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '8'

      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@12.1
        with:
          cli: 1.10.1.693              # Clojure CLI based on tools.deps
          clj-kondo: 2022.05.31        # Clj-kondo
          cljfmt: 0.10.2               # cljfmt

      - name: clj-fmt fix
        run: cljfmt check src

      - name: linter
        run: clj-kondo --lint src test

      - name: run tests
        run: clojure -Mtest