name: Clojure CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Clojure CLI
        uses: DeLaGuardo/setup-clojure@12.5
        with:
          clj-kondo: latest
          cljfmt: latest

      - name: Install Leiningen
        run: |
          curl https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein > lein
          chmod +x lein
          sudo mv lein /usr/local/bin/
          
      - name: Check format
        run: cljfmt fix

      - name: Lint lab1 - problem7
        run: |
              cd lab1/problem7 
              clj-kondo --lint src

      - name: Lint lab1 - problem26
        run: |
              cd lab1/problem26
              clj-kondo --lint src
              
      - name: Test lab1 - problem7
        run: |
              cd lab1/problem7 
              lein test 
              
      - name: Test lab1 - problem26
        run: |
              cd lab1/problem26 
              lein test 

      - name: Lint lab2
        run: |
              cd lab2/rb-tree
              clj-kondo --lint src
              
      - name: Test lab2 - rb-tree
        run: |
              cd lab2/rb-tree 
              lein test
